### ISSUE TITLE
Error messages

### ISSUE THREAD

**Issue by Inspiredbubbles** [RANGROO/herikamindmap#1]
Hi, I am not sure if this is an issue of the herikamindmap or if I am doing something wrong with the chromadb. When I go to  the gateway server, the memories session appear as "pending". I update the chromadb api address everytime on the conf.php (via the gateway server). If I try to open that address I get a blank page. 

When I run the herikamindmap I get the error(s) that you can see on the screenshot. I even have the dwemerdistro uninstalled and reinstalled entirely, and clicked on hte "reinstall" button on the gateway server to no avail (only to have her previous memories deleted...)

Any clues on what could be happening? 

ANd sorry if this is the wrong place to post it! 

![herika_memory](https://github.com/RANGROO/herikamindmap/assets/81482347/22992a80-5adf-4eda-9c01-b502c08cae43)

**Comment by RANGROO** [comment]
With the reinstall of the Distro no memories may of been generated yet so the herika_memories collection has not been created so the URL wont work.

Try talking to Herika ingame with memories enabled then try again. If it connects then you are good to go, just remember it won't show any data plots until 50 memories are generated.

**Comment by Inspiredbubbles** [comment]
Hei!

Sorry for the delay replying, but yes, it worked!  I was eventually able to to generate her brain! ANd with that said, I also note she sometimes might get a bit repetitive, in the sense she responds with the same sentence if I say something more or less similar to something I said before, even if the context is quite different. I wonder how that would be if I was using gpt 4 but unfortunately that is quite expensive for me at the moment. 

Thank you once again for the great mod and everything associated with it! I am having a lot of fun :D
